### ISSUE TITLE
Warnings when converting .glTF samples to X3D JSON (.x3dj)

### ISSUE THREAD

**Issue by coderextreme** [create3000/x3d-tidy#16]
I get many warnings when converting glTF samples:

https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0

with the command:

```bash
for i in `find . -name '*gltf'`; do echo $i; npx x3d-tidy -i $i -o `dirname $i`/`basename $i .gltf`.x3dj; done
````

Many .x3dj files are created, but I don't understand why there are so many warnings reported:

Sample output:

```./MetalRoughSpheres/glTF/MetalRoughSpheres.gltf
(node:8504) ExperimentalWarning: CommonJS module C:\Users\jcarl\AppData\Roaming\npm\node_modules\npm\node_modules\debug\src\node.js is loading ES Module C:\Users\jcarl\AppData\Roaming\npm\node_modules\npm\node_modules\supports-color\index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29888) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:29888) V8: C:\Users\jcarl\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\assets\components\Texturing3DComponent.js:16 Invalid asm.js: Invalid member of stdlib
(node:29888) V8: C:\Users\jcarl\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\assets\components\Texturing3DComponent.js:53 Invalid asm.js: Invalid member of stdlib
./MetalRoughSpheres/glTF-Embedded/MetalRoughSpheres.gltf
(node:24708) ExperimentalWarning: CommonJS module C:\Users\jcarl\AppData\Roaming\npm\node_modules\npm\node_modules\debug\src\node.js is loading ES Module C:\Users\jcarl\AppData\Roaming\npm\node_modules\npm\node_modules\supports-color\index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4508) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:4508) V8: C:\Users\jcarl\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\assets\components\Texturing3DComponent.js:16 Invalid asm.js: Invalid member of stdlib
(node:4508) V8: C:\Users\jcarl\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\assets\components\Texturing3DComponent.js:53 Invalid asm.js: Invalid member of stdlib
Couldn't load URL 'file:///C:/Users/jcarl/glTF-Sample-Models/2.0/MetalRoughSpheres/glTF-Embedded/MetalRoughSpheres.gltf'. TypeError: Only HTTP(S) protocols are supported
    at getNodeRequestOptions (C:\Users\jcarl\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\node-fetch\lib\index.js:1331:9)
    at C:\Users\jcarl\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\node-fetch\lib\index.js:1450:19
    at new Promise (<anonymous>)
    at fetch (C:\Users\jcarl\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\node-fetch\lib\index.js:1447:9)
    at value (C:\Users\jcarl\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite-node\src\index.js:129:20)
    at GLTF2Parser.bufferObject (C:\Users\jcarl\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\x_ite.js:45574:30)
    at C:\Users\jcarl\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\x_ite.js:45562:78
    at Array.map (<anonymous>)
    at GLTF2Parser.buffersArray (C:\Users\jcarl\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\x_ite.js:45562:52)
    at GLTF2Parser.rootObject (C:\Users\jcarl\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\x_ite.js:45190:19)
Couldn't load X3D file.```

**Comment by create3000** [comment]
Yes there is at least one critical warning. Looks like x_ite-node's fetch must implement to handle "data:"  URLs. I have done that now and released a new version, also for x3d-tidy, which is now `x3d-tidy@2.0.6`.

I cannot avoid the other warnings. A lot warnings come from `node` itself and will maybe disappear in future versions of `node`.

**Comment by coderextreme** [comment]
If you can advise which version of node.js to use, that would help!

**Comment by create3000** [comment]
I always use the latest version of Node.js, if the warnings bother you, but only if everything runs smoothly, you know, just `2>/dev/null`.

**Comment by create3000** [comment]
```sh
holger@Weiputer x_ite % node -v
v23.3.0
```
