### ISSUE TITLE
For glTF to .x3d output, X3D DTD and X3D XSD declarations should start with https://, not http://

### ISSUE THREAD

**Issue by coderextreme** [create3000/x3d-tidy#22]
Before:

```
$ java -cp /c/Users/jcarl/Downloads/X3DJSAIL.4.0.full.jar org.web3d.x3d.jsail.CommandLine -validate ./SheenDamask/glTF/SheenDamask.x3d
CommandLine parameter: "-validate" for model validation
parameter: source file SheenDamask.x3d filesize 3127980 bytes
Parsing using Document Object Model (DOM) based X3DLoaderDOM...
Dec 04, 2024 2:53:58 AM org.web3d.x3d.jsail.X3DLoaderDOM loadModelFromFileX3D
SEVERE: null
org.xml.sax.SAXException: Fatal Error: URI=http://www.web3d.org/specifications/x3d-4.0.dtd Line=1: The markup declarations contained or pointed to by the document type declaration must be well-formed.
        at org.web3d.x3d.jsail.X3DLoaderDOM$MyErrorHandler.fatalError(X3DLoaderDOM.java:1720)
        at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
        at org.apache.xerces.impl.XMLDTDScannerImpl.scanDecls(Unknown Source)
        at org.apache.xerces.impl.XMLDTDScannerImpl.scanDTDExternalSubset(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentScannerImpl$DTDDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:206)
        at org.web3d.x3d.jsail.X3DLoaderDOM.loadModelFromFileX3D(X3DLoaderDOM.java:246)
        at org.web3d.x3d.jsail.X3DLoaderDOM.loadModelFromFileX3D(X3DLoaderDOM.java:231)
        at org.web3d.x3d.jsail.X3DLoaderDOM.loadModelFromFileX3D(X3DLoaderDOM.java:205)
```
After:
```
$ java -cp /c/Users/jcarl/Downloads/X3DJSAIL.4.0.full.jar org.web3d.x3d.jsail.CommandLine -validate ./SheenDamask/glTF/SheenDamask.x3d
CommandLine parameter: "-validate" for model validation
parameter: source file SheenDamask.x3d filesize 3127982 bytes
Parsing using Document Object Model (DOM) based X3DLoaderDOM...
[warning] component name newValue='X_ITE' includes an unrecognized optional value not matching any of the required enumeration string tokens.
       Supported values are Core, CADGeometry, CubeMapTexturing, DIS, EnvironmentalEffects, EnvironmentalSensor, EventUtilities, Followers, Geometry2D, Geometry3D, Geospatial, Grouping, HAnim, H-Anim, Interpolation, KeyDeviceSensor, Layering, Layout, Lighting, Navigation, Networking, NURBS, ParticleSystems, Picking, PointingDeviceSensor, TextureProjection, Rendering, RigidBodyPhysics, Scripting, Shaders, Shape, Sound, Text, Texturing, Texturing3D, Time, VolumeRendering
[error] X3DLoaderDOM: Parent-child node relationship not found! (parent ImageTexture, child TextureProperties, containerField='textureProperties') Please report this problem to brutzman@nps.edu
[error] X3DLoaderDOM: Incorrectly handled X3DJSAIL object construction, current elementObject=ImageTexture (ImageTexture), child="TextureProperties", containerField="textureProperties", java.lang.ClassCastException: class org.web3d.x3d.jsail.Texturing.ImageTexture cannot be cast to class org.web3d.x3d.sai.Grouping.X3DGroupingNode (org.web3d.x3d.jsail.Texturing.ImageTexture and org.web3d.x3d.sai.Grouping.X3DGroupingNode are in unnamed module of loader 'app')
    This error can be caused by incorrect parent-child node relationships or incorrect containerField values.
    X3D node typing is strict, check or validate your scene graph!
    This error can also be caused by X3DLoaderDOM DOM omissions in X3DJSAIL. Please report mysterious problems, thank you.
        at org.web3d.x3d.jsail.CommandLine.run(CommandLine.java:922)
        at org.web3d.x3d.jsail.CommandLine.main(CommandLine.java:242)
```
etc.

I believe this is a good XML header:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE X3D PUBLIC "ISO//Web3D//DTD X3D 4.0//EN" "https://www.web3d.org/specifications/x3d-4.0.dtd">
<X3D profile='Interchange' version='4.0' xmlns:xsd='http://www.w3.org/2001/XMLSchema-instance' xsd:noNamespaceSchemaLocation='https://www.web3d.org/specifications/x3d-4.0.xsd'>
```
note the use of https; instead of http:

**Comment by create3000** [comment]
JSON converted files usually start with:

```json
{ "X3D": {
    "encoding": "UTF-8",
    "@profile": "Interchange",
    "@version": "4.0",
    "@xsd:noNamespaceSchemaLocation": "http://www.web3d.org/specifications/x3d-4.0.xsd",
    "JSON schema": "http://www.web3d.org/specifications/x3d-4.0-JSONSchema.json",
    "head": {
```

What about these URLs?

**Comment by coderextreme** [comment]
The JSON schema x3dvalidate program (uses Ajv) doesn't validate those, just
make sure they look valid.  It doesn't try to download any URLs except
perhaps the JSON metaschema (which I also store locally).  My guess is
X3DJSAIL actually tries to download the DTD and the XSD for its work (bad
idea, it  should use local resources).

John

**Comment by coderextreme** [comment]
My guess is these should be https:// as well.

Are you reporting a bug?

    ***@***.***:noNamespaceSchemaLocation":
"http://www.web3d.org/specifications/x3d-4.0.xsd",
    "JSON schema":
"http://www.web3d.org/specifications/x3d-4.0-JSONSchema.json",

**Comment by create3000** [comment]
Ok, will change these, too.
