### ISSUE TITLE
x3d-tidy loads external resources from X3DUrlObject nodes

### ISSUE THREAD

**Issue by coderextreme** [create3000/x3d-tidy#7]
I'm having difficulty with validating external (in a separate file) and embedded shaders (in the X3D).  Neither way will validate in an .x3d file.

John

**Comment by create3000** [comment]
Could you please explain what you are exactly doing, maybe with example command line.

**Comment by coderextreme** [comment]
npx x3d-tidy -i `pwd`/ball.json -o `pwd`/ball.wrl

Files are here: https://github.com/coderextreme/X3DJSONLD/tree/master/src/main/data

I did try embedding the shaders.  See external shader inclusion in ball.json.  I don't know whether you are moving to embedded shaders or not. If you are requiring embedded shaders, can x3d-tidy do it with a flag?

Thanks!

Couldn't load URL 'file:///C:/Users/john/X3DJSONLD/src/main/shaders/x_ite.vs'. Error: Error in ShaderPart '' in URL 'file:///C:/Users/john/X3DJSONLD/src/main/shaders/x_ite.vs', line 1, ERROR: 0:1: 'version' : #version directive must occur before anything else, except for comments and white space
ERROR: 0:22: 'in' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:23: 'in' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:25: 'out' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:26: 'out' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:27: 'out' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:28: 'out' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:29: 'out' : storage qualifier supported in GLSL ES 3.00 and above only

    at ShaderPart.<anonymous> (C:\Users\john\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\x_ite.js:97100:25)
    at FileLoader.loadDocumentAsync (C:\Users\john\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\x_ite.js:64879:13)

Couldn't load URL 'file:///C:/Users/john/X3DJSONLD/src/main/shaders/x_itebubbles.fs'. Error: Error in ShaderPart '' in URL 'file:///C:/Users/john/X3DJSONLD/src/main/shaders/x_itebubbles.fs', line 1, ERROR: 0:1: 'version' : #version directive must occur before anything else, except for comments and white space
ERROR: 0:16: 'in' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:16: '' : No precision specified for (float)
ERROR: 0:17: 'in' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:17: '' : No precision specified for (float)
ERROR: 0:18: 'in' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:18: '' : No precision specified for (float)
ERROR: 0:19: 'in' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:19: '' : No precision specified for (float)
ERROR: 0:20: 'in' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:20: '' : No precision specified for (float)
ERROR: 0:22: 'out' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:22: '' : No precision specified for (float)
ERROR: 0:27: '' : No precision specified for (float)
ERROR: 0:27: 'texture' : no matching overloaded function found
ERROR: 0:27: '=' : dimension mismatch
ERROR: 0:27: '=' : cannot convert from 'const mediump float' to '4-component vector of float'
ERROR: 0:28: '' : No precision specified for (float)
ERROR: 0:30: 'texture' : no matching overloaded function found
ERROR: 0:30: 'r' :  field selection requires structure or vector on left hand side
ERROR: 0:31: 'texture' : no matching overloaded function found
ERROR: 0:31: 'g' :  field selection requires structure or vector on left hand side
ERROR: 0:32: 'texture' : no matching overloaded function found
ERROR: 0:32: 'b' :  field selection requires structure or vector on left hand side

    at ShaderPart.<anonymous> (C:\Users\john\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\x_ite.js:97100:25)
    at FileLoader.loadDocumentAsync (C:\Users\john\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\x_ite.js:64879:13)

**Comment by coderextreme** [comment]
Here is an online version (with X_ITE) of a similar thing.  I recently made some changes to my shaders to try to get them to work...

https://coderextreme.net/X3DJSONLD/src/main/html/index.html

John

**Comment by coderextreme** [comment]
Maybe the shaders are being cached, so I'm getting really old copies? I'll flush cache, clear cookies, et.

**Comment by coderextreme** [comment]
Okay, I'm starting to integrate this into my mainline regression tests.  I don't want to spam the internet with downloading a lot of images and shaders.  I just want to convert  many  .x3d's to many .x3dj.  I'll JSON validation, for now.  Also, can you take a list of files to convert on input, and produce a list of converted files. I'd like to specify what to change the output file extension to.  That is, I want to use x3d-tidy in batch mode.  Thanks!

**Comment by create3000** [comment]
> I don't want to spam the internet with downloading a lot of images and shaders.

I think you mean that when converting files which contain URLs with external files, that these external files are not loaded.

>Also, can you take a list of files to convert on input, and produce a list of converted files on output.

I will not change x3d-tidy this way, because there are a lot of programming languages like `sh, bash, perl, or with node` where you can make a `for loop` top achieve this result.

**Comment by coderextreme** [comment]
Yes, I am currently using ```... | xargs -O -L 1 npx runtidy.sh``` to process a list of files.  The key is to make your command tool work like the rest of the command line tools. If I want to run runtidy.sh in parallel, I just use ```xargs -P 8`` for running on 8 processors.  Can you for loop do that?  You don't *have* to do it, but it will make your command more useful as a Linux tool.

**Comment by coderextreme** [comment]
Here's how I turned Saxon into a beast:

https://[coderextreme.net/X3DJSONLD/src/main/java/net/coderextreme/RunSaxon.java](https://coderextreme.net/X3DJSONLD/src/main/java/net/coderextreme/RunSaxon.java)

Enjoy!

**Comment by coderextreme** [comment]
I've updating my x3d-tidy enhancement to take a list of files on the command line, and produce a list of  generated files on standard output (use a flag like -print of course).

**Comment by create3000** [comment]
You can already output the files to stdout if you only provide the extension for the `-o` switch:

```sh
npx x3d-tidy -i tests/test.x3d -o .x3dv
```

Worth to mention again, you can use relative paths now.

**Comment by coderextreme** [comment]
I don't want to output files to stdout, I want to output filenames to
stdout.  Sorry for the confusion.  See my Saxon example.

I want to take .x3dj filenames from on standard input and run them through
my own converter that converts to Java, JavaScript, etc.  I can do all of
this with my json2all.js command.

If I use json2all.js with xargs, I can put all the conversions on
separate processors, or one processor with a -P ${PROCESSORS} argument.  At
least I'm not telling you to parallelize your program!  That can be done
with xargs.  No need to reinvent the wheel.

I've also heard there's a ```$ para`` or GNU parallel program. I haven't
used it yet, because I use xargs.


John

**Comment by coderextreme** [comment]
BTW, I'm starting to use fewer for loops in bash scripts. See:

https://github.com/coderextreme/X3DJSONLD/blob/master/src/main/shell/several.sh

See how I replaced for loops with while loops.

This is due to spaces in filenames.  For loops with filenames are now bad
practice in bash.


YMMV,

John

**Comment by coderextreme** [comment]
So here's what I do because of your recalcitrance:

My script is like this.  I have to call bash, npx and x3d-tidy for each
file.  I have nearly 200 file for normal runs. 4000 plus in production.
I've been trying to avoid the check for a new x3d-tidy each time.  I'm
still working on that.  Maybe I'll write a competitor to x3d-tidy.  Hmm!

ls -d "$@" | grep -v intermediate | grep -v "\.new" | tr '\n' '\0' | xargs
-0 -L 1 bash runtidy.sh | sed '/^$/d' | sed 's/^\(.*\)$/"\1"/' | xargs -P
"$PROCESSORS" "${NODE}" "${NODEDIR}/json2all.js"

$ cat runtidy.sh
#!/bin/bash -x

export IN=`pwd`/"$1"
export OUT=`pwd`/`dirname "$1"`/`basename "$1" .x3d`.x3dj
echo npx x3d-tidy -i "$IN" -o "$OUT"
npx x3d-tidy -i "$IN" -o "$OUT"
echo "$OUT"

**Comment by coderextreme** [comment]
I'm seeing that x3d-tidy produces JSON results much more compatible with
X_ITE.

Any clues on the shader issue?

Thanks!

John

**Comment by coderextreme** [comment]
Here's what I'm trying to do currently:  I don't know what you are doing about the MFString business.

$ npx --yes x3d-tidy -i /c/Users/john/X3DJSONLD/src/main/shell/../personal/flowerproto.x3d -o /c/Users/john/X3DJSONLD/src/main/shell/../personal/flowerproto.x3dj
$ npx --yes x3d-tidy -i /c/Users/john/X3DJSONLD/src/main/shell/../personal/sphereflowers.x3d -o /c/Users/john/X3DJSONLD/src/main/shell/../personal/sphereflowers.x3dj

[https://github.com/coderextreme/X3DJSONLD/blob/master/src/main/shaders/x_ite_flowers_chromatic.vs](url)

[https://github.com/coderextreme/X3DJSONLD/blob/master/src/main/shaders/x_ite.fs](url)

[https://github.com/coderextreme/X3DJSONLD/blob/master/src/main/personal/sphereflowers.x3dj](url) -- raw, not blank

[https://github.com/coderextreme/X3DJSONLD/blob/master/src/main/personal/sphereflowers.x3d](url)

[https://github.com/coderextreme/X3DJSONLD/blob/master/src/main/personal/flowerproto.x3dj](url)

[https://github.com/coderextreme/X3DJSONLD/blob/master/src/main/personal/flowerproto.x3d](url)

**Comment by create3000** [comment]
There is now a new version 8.12.0, which does not load external resources.

**Comment by create3000** [comment]
x3d-tidy is now @2.0.9. Please read documentation for new syntax.

https://www.npmjs.com/package/x3d-tidy?activeTab=readme

You can remove `-i` and `-o` in some cases. Specify multiple in and out files, or only multiple out files. Example syntaxes here: https://www.npmjs.com/package/x3d-tidy?activeTab=readme#examples

**Comment by coderextreme** [comment]
Can you make x3d-tidy so that it takes multiple input filenames on stdin
(but as arguments with the next thing is ok, but limited) an output file
extension/encoding (or multiple) as an argument to x3d-tidy, and optionally
produces output filenames on stdout, in addition to converting?  This would
fit a lot better in my workflow.  Then replacing my RunSaxon for XML to
JSON conversion would be easy.  I’ll retain RunSaxon if I want to batch
process any stylesheets.

I think you already said that x3d-tidy could take a file extension alone
for output filename extensions?  Has that changed with 2.0?  Can I specify
multiple extensions (leading with a “.”, I guess)

John

**Comment by create3000** [comment]
Yes, you could specify multiple extension so that the output goes to stdout:

`npx x3d-tidy in1.x3d .x3dj in2.x3d .x3dj`

Don't if this makes much sense.

`xargs` can do lot of magic on the command line with the args. It should do what you want. 

https://www.man7.org/linux/man-pages/man1/xargs.1.html
