### ISSUE TITLE
Please reduce number of error reports.

### ISSUE THREAD

**Issue by coderextreme** [create3000/x3d-tidy#8]
Test x3d-tidy with this document:

https://sourceforge.net/p/x3d/code/HEAD/tree/www.web3d.org/x3d/stylesheets/java/examples/HelloWorldProgramOutput.x3d

Thanks!

John

**Comment by coderextreme** [comment]
Couldn't load URL 'https://x3dgraphics.com/examples/X3dForWebAuthors/Chapter14Prototypes/ArtDecoPrototypesExcerpt.x3dv#ArtDeco02Material'. Error: PROTO not found
    at X3DExternProtoDeclaration.setInternalScene (C:\Users\john\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\x_ite.js:65063:16)
    at X3DExternProtoDeclaration.setInternalSceneAsync (C:\Users\john\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\x_ite.js:65047:16)
    at C:\Users\john\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\x_ite.js:64750:13

Error loading extern prototype 'ArtDeco02Material': Error: File could not be loaded.
    at X3DExternProtoDeclaration.setInternalSceneAsync (C:\Users\john\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\x_ite.js:65050:26)
    at FileLoader.createX3DFromURLAsync (C:\Users\john\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\x_ite.js:64778:10)
    at FileLoader.loadDocumentError (C:\Users\john\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\x_ite.js:64903:16)
    at C:\Users\john\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\x_ite.js:64755:16

Couldn't load URL 'https://x3dgraphics.com/examples/X3dForWebAuthors/Chapter14Prototypes/ArtDecoPrototypesExcerpt.x3d#ArtDeco02Material'. Error: PROTO not found
    at X3DExternProtoDeclaration.setInternalScene (C:\Users\john\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\x_ite.js:65063:16)
    at X3DExternProtoDeclaration.setInternalSceneAsync (C:\Users\john\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\x_ite.js:65047:16)
    at C:\Users\john\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x_ite\dist\x_ite.js:64750:13

Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.

I'm not sure if these are good web links or not.

**Comment by coderextreme** [comment]
https://x3dgraphics.com/examples/X3dForWebAuthors/Chapter14Prototypes/ArtDecoPrototypesExcerpt.x3dv appears to be there, but if you aren't downloading, then you won't find the PROTO

**Comment by create3000** [comment]
Please try with new version, which I have released right now.
